services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: local_ai_gpp_backend
    ports:
      - "8000:8000"
    volumes:
      - ./models_storage:/app/models_storage

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: local_ai_gpp_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
